//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-widget_library\CustomPlugin\src\main\java\com\ashera\custom\CustomEventCommand.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CustomEventCommand")
#ifdef RESTRICT_CustomEventCommand
#define INCLUDE_ALL_CustomEventCommand 0
#else
#define INCLUDE_ALL_CustomEventCommand 1
#endif
#undef RESTRICT_CustomEventCommand

#if !defined (ASCustomEventCommand_) && (INCLUDE_ALL_CustomEventCommand || defined(INCLUDE_ASCustomEventCommand))
#define ASCustomEventCommand_

#define RESTRICT_EventCommand 1
#define INCLUDE_ASEventCommand 1
#include "EventCommand.h"

@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASCustomEventCommand : NSObject < ASEventCommand >

#pragma mark Public

- (instancetype)init;

- (id)executeCommandWithASIWidget:(id<ASIWidget>)widget
                  withJavaUtilMap:(id<JavaUtilMap>)eventObject
                withNSObjectArray:(IOSObjectArray *)params;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomEventCommand)

FOUNDATION_EXPORT void ASCustomEventCommand_init(ASCustomEventCommand *self);

FOUNDATION_EXPORT ASCustomEventCommand *new_ASCustomEventCommand_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomEventCommand *create_ASCustomEventCommand_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomEventCommand)

@compatibility_alias ComAsheraCustomCustomEventCommand ASCustomEventCommand;


#endif

#pragma pop_macro("INCLUDE_ALL_CustomEventCommand")
