//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-widget_library\CustomPlugin\src\main\java\com\ashera\custom\LowerCaseSuffixFilter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LowerCaseSuffixFilter")
#ifdef RESTRICT_LowerCaseSuffixFilter
#define INCLUDE_ALL_LowerCaseSuffixFilter 0
#else
#define INCLUDE_ALL_LowerCaseSuffixFilter 1
#endif
#undef RESTRICT_LowerCaseSuffixFilter

#if !defined (ASLowerCaseSuffixFilter_) && (INCLUDE_ALL_LowerCaseSuffixFilter || defined(INCLUDE_ASLowerCaseSuffixFilter))
#define ASLowerCaseSuffixFilter_

#define RESTRICT_IFilter 1
#define INCLUDE_ASIFilter 1
#include "IFilter.h"

@interface ASLowerCaseSuffixFilter : NSObject < ASIFilter >

#pragma mark Public

- (instancetype)init;

- (jboolean)filterWithNSString:(NSString *)value
                  withNSString:(NSString *)query;

@end

J2OBJC_EMPTY_STATIC_INIT(ASLowerCaseSuffixFilter)

FOUNDATION_EXPORT void ASLowerCaseSuffixFilter_init(ASLowerCaseSuffixFilter *self);

FOUNDATION_EXPORT ASLowerCaseSuffixFilter *new_ASLowerCaseSuffixFilter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASLowerCaseSuffixFilter *create_ASLowerCaseSuffixFilter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASLowerCaseSuffixFilter)

@compatibility_alias ComAsheraCustomLowerCaseSuffixFilter ASLowerCaseSuffixFilter;

#endif

#pragma pop_macro("INCLUDE_ALL_LowerCaseSuffixFilter")
